/*
 * JBoss, Home of Professional Open Source
 * Copyright 2008, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2008,
 * @author JBoss Inc.
 */
//
// Copyright (C) 2001,
//
// HP Arjuna Labs
// Newcastle upon Tyne,
// Tyne and Wear,
// UK.
//
// $Id: TestRunProperties.java 170 2008-03-25 18:59:26Z jhalliday $

package org.jboss.dtf.testframework.manager;

/**
 *
 * @author  administrator
 */
public class TestRunProperties extends javax.swing.JDialog {

    protected CoordinatorManager _manager = null;

    /** Creates new form TestRunProperties */
    public TestRunProperties(CoordinatorManager manager, java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        _manager = manager;

        setTitle("Begin Test Run - Properties");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _testDefURL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _testSelURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _softwareVersion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        _runButton = new javax.swing.JButton();
        _cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;

        setTitle("Test Run Properties");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;

        jPanel2.setPreferredSize(new java.awt.Dimension(450, 120));
        jLabel1.setText("Test Definition File URL (.xml):");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        jPanel2.add(jLabel1, gridBagConstraints3);

        _testDefURL.setToolTipText("http://testdefinitionfile.xml");
        _testDefURL.setText("http://");
        _testDefURL.setPreferredSize(new java.awt.Dimension(260, 21));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        jPanel2.add(_testDefURL, gridBagConstraints3);

        jLabel2.setText("Test Selection URL (.xml):");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel2, gridBagConstraints3);

        _testSelURL.setToolTipText("http://testselectionfile.xml");
        _testSelURL.setText("http://");
        _testSelURL.setPreferredSize(new java.awt.Dimension(260, 21));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 1;
        jPanel2.add(_testSelURL, gridBagConstraints3);

        jLabel3.setText("Software Version:");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel3, gridBagConstraints3);

        _softwareVersion.setToolTipText("xxx.xxx.xxx.xxx");
        _softwareVersion.setPreferredSize(new java.awt.Dimension(260, 21));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 2;
        jPanel2.add(_softwareVersion, gridBagConstraints3);

        _runButton.setIcon(new javax.swing.ImageIcon("run.gif"));
        _runButton.setToolTipText("Begin test run");
        _runButton.setText("Run");
        _runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _runButtonActionPerformed(evt);
            }
        });

        jPanel1.add(_runButton);

        _cancelButton.setToolTipText("Do not perform run");
        _cancelButton.setText("Cancel");
        _cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(_cancelButton);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 3;
        jPanel2.add(jPanel1, gridBagConstraints3);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        getContentPane().add(jPanel2, gridBagConstraints2);

        pack();
    }//GEN-END:initComponents

    private void _runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__runButtonActionPerformed
        String testDefURL = _testDefURL.getText();
        String testSelURL = _testSelURL.getText();
        String softwareVersion = _softwareVersion.getText();

        if ( (testDefURL.length()==0) || (testSelURL.length()==0) || (softwareVersion.length()==0) )
        {
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
        else
        {
            _manager.performTestRun(testDefURL, testSelURL, softwareVersion);
            closeDialog(null);
        }
    }//GEN-LAST:event__runButtonActionPerformed

    /**
     * The cancel button even handler
     */
    private void _cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cancelButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event__cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField _testDefURL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField _testSelURL;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField _softwareVersion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton _runButton;
    private javax.swing.JButton _cancelButton;
    // End of variables declaration//GEN-END:variables

}
